{% set name = "elyra-pipeline-editor-extension" %}
{% set version = "1.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-pipeline-editor-extension-{{ version }}.tar.gz
  sha256: da134c224e968a1df643f74b99263a6ee21a557bda5615d779474e77a1f7e90c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - elyra-server ==1.5.2
    - python >=3.6

test:
  commands:
    - exit 0

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
